### ISSUE TITLE
With older apk got sync error

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1066]
**Describe the bug**
Not able to login with older apk got error sync fail
I am trying to login with jssuat and power I got this error undefined  is not an object (evaluating 'k.isQuestionGroup) 

**To Reproduce**
1. login with that org 
2. try to syn with org 
3.  See error

**Expected behavior**
<img width="327" alt="Screenshot 2023-08-07 at 10 22 15 AM" src="https://github.com/avniproject/avni-client/assets/104890488/a054f6bd-15e4-48b1-8df9-596f09dec980">

user should able to sync that organisation
**Screenshots**
older apk
https://app.circleci.com/pipelines/github/avniproject/avni-client/1841/workflows/dd8ce6b1-729f-48a1-8569-90132cc43457/jobs/11540/artifacts

**Comment by petmongrels** [comment]
Not reproducible on AchalaB@power.

Reproducible for JSSCP UAT. But this is a data issue. The prod data has individual with observation of concept that doesn't exist.   36525e7b-575f-4b34-aae8-9a031adb84eb concept uuid.

One individual has this obs:

"observations": {
    "36525e7b-575f-4b34-aae8-9a031adb84eb": "Mother",
    "3d95a3b6-b6a2-4335-a680-e14095cd9dfb": "test",
    "6a0d80bf-e271-4012-a8e1-9d9c91b18a14": "e7b50c78-3d90-484d-a224-9887887780dc",
    "c218b516-a47f-411a-ad82-c3f1f446d9b0": 2,
    "f1aec43b-c985-442a-97dd-70cbe00e3643": "8e7eee58-19a7-4189-a29b-a90c801765ba",
    "476a0b71-485b-4a0a-ba6f-4f3cf13568ca": "e7b50c78-3d90-484d-a224-9887887780dc",
    "beef9533-cfa1-4efa-bed3-d14169468c1c": [
      "2ecc9fee-493c-4ce5-bd5d-c3139a2fa48f"
    ],
    "fb3214f4-d040-40bc-bd38-883ad5e0cae7": "54eb4ba3-e940-4d36-ba56-d303f066c088",
    "cc4e6c8f-99ea-4d47-a672-a6e5b513806d": "Father",
    "d6bb1543-0c1c-4c01-bd47-3883701d945b": "c6e3c748-a2c2-4663-af41-48bdb9e7fa12"
  }

since it is a UAT organisation we can ignore this error. probably caused by concept being in org 1 and jssuat doesn't have parent org.

**Comment by AchalaBelokar** [comment]
Find error sncu I don’t know whether it is data error or what..

**Comment by petmongrels** [comment]
what is the user

**Comment by AchalaBelokar** [comment]
taqim@sncu

**Comment by petmongrels** [comment]
got this error (in screenshot). this is due to db dump has been created with new version of mobile app code. in such cases we should delete the mobile backup for that user.

sync passed after that.


![Image](https://github.com/avniproject/avni-client/assets/105867/a3dbe0da-8f50-40d9-ad1f-37bf0db57793)
