### ISSUE TITLE
App crashes when editing a form whose linked subject is voided.

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/avni-client#1074]
**To Reproduce**
1. Create a form (say F) with subject type field.
2. Try linking a subject (say individual 'Alice') to it and save the form.
3. Void the individual 'Alice'.
4. Now edit the form F. The app will crash immediately upon opening the form.

**Expected behavior**
The application should not crash when editing a form whose linked subject is voided.

**Screenshots**(gif)
![3aa7d882-79a6-4f61-963f-f3596490e22d (1)](https://github.com/avniproject/avni-client/assets/44082588/d74b248c-9709-42c6-b182-1baeaa431278)

**Comment by ashusvnath** [comment]
2 findings:

1. 't.repetable' is not found in app code for client anywhere most completions say '...element.repetableQuestionGroup' or '...element.repetableGroup'

2. Both subject encounter and registration forms with the above setup (a voided subject linked to a form that needs to be edited) were tried out and the situation could not be reproduced.

I suspect this has something to do with validation/decision rules.

**Comment by ashusvnath** [comment]
Fix identified in avniproject/avni-models and fixed. Version 1.30.57 has the relevant fix.

**Comment by himeshr** [comment]
@ashusvnath Code review comment, with action for next time https://github.com/avniproject/avni-models/commit/13fea6b8efd1c3c8c333fdb164f92cc37924a716#r124618585

**Comment by himeshr** [comment]
Was able to reproduce this issue in staging env, Goonj_revamp org, for beulah@gpart user.
On the old apk, when i tried opening a distribution with a voided Activity, app used to crash.
But with new apk, i am able to open distribution(test) , type "CFW", which has voided activity(test).

Note that, we encountered an error while editing Activities in Goonj_revamp, which was caused due to change in Activity registration form. Ignoring this data error, as their is a task already in Goonj project.


https://github.com/avniproject/avni-client/assets/72493481/71132e70-a9ea-4cc9-a980-19cdbe368d35
