### ISSUE TITLE
Custom Dashboard Filters Display breaking for Gender

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1107]
**Describe the bug**
Filter is not working properly
we need to apply filter by gender

**To Reproduce**
1. login with AchalaB@sakhiapp
2. Click on on filter
3. select any gender male female 
4. apply filter

**Expected behavior**
which filter is applying should be shown clearly
**Screenshots**

![filter work](https://github.com/avniproject/avni-client/assets/104890488/2fb6ffe5-a866-41e0-95cf-83d1fdfbcc5a)

**Comment by mahalakshme** [comment]
In circle-ci we are calling deploy_platform_translations_prerelease, so need to dig more

**Comment by ashusvnath** [comment]
This behaviour is seen in the 4.0 APK also.

**Comment by mahalakshme** [comment]
but still we need to fix this issue

**Comment by ashusvnath** [comment]
```params::: [{"type":"Gender","dataType":null,"filterValue":[{"that":{}},{"that":{}},{"that":{}},{"that":{}}]}]```

**Comment by ashusvnath** [comment]
The problem is not with translations but the way `@ungap/structured-clone` is serializing and saving filters in the Realm DB's CustomDashboardCache.
The above seen value is result of deserialzing the filters from the fast synced realm db's CustomDashboardCache

**Comment by 1t5j0y** [comment]
Use of `structured-clone` was causing changes during serialization/deserialization and conversion of the deserialized value to state which was causing the observed issue. Also, the JSON columns in CustomDashboardCache were no longer readable JSONs with the change to use this library.

Made changes to rely on `JSON.stringify` and remove the use of `structured-clone` for serialization of `CustomDashboardCache` fields. All fields except `selectedValues` worked immediately. `selectedValues` caused a problem when `Address` type filters were used and multiple locations were selected (due to locations containing `locationMappings` which caused cyclic reference issues). Removed locationMappings from the object used in the filters on the CustomDashboard screens and this issue went away.

During testing, noticed filterConfig with value '0' as uuid which was causing run time errors due to methods being called on an undefined object. Not sure if this was due to the use of structured-clone and if such cases exist in prod but added some additional code to handle this scenario to fail gracefully and not crash.
