### ISSUE TITLE
Unable to add some relations to household

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1114]
Steps to reproduce:

Env: prerelease, version: 5.0 and 4.0.1 - with both issue reproducible, raised during 5.0 release signoff
- Login to himeshr@jsscp, password in bugbash sheet
- Click on Search -> Select household - Click on 'aaa' household
- Click on Add member
- Select 'Wife' relationship 
- Click on "Search existing individual" and select a female
- "Nondeterminate relationship" error appears.
- Repeat the same for 'sister-in-law' - same issue occurs.
- The issue didn't occur when tried with 'daughter', 'sister' and 'mother-in-law'.

Analysis details:
There doesn't seem to be any issue with the implementation. But not yet checked the data in the db.

**Comment by vinayvenu** [comment]
Related to https://github.com/avniproject/avni-product/issues/1283 and/or https://github.com/avniproject/avni-client/issues/1013

**Comment by mahalakshme** [comment]
I should have checked the existing issues before creating a new issue. But this issue is not related to both above mentioned. since they occured when I tried to add a relative who is an individual.

**Comment by vinayvenu** [comment]
@mahalakshme If this is reproducible in 4.0.1, does it need to go to 6.0 instead?

**Comment by mahalakshme** [comment]
yeah have moved it to 6.0. thought of the same, but thought of scheduling few bugs in every release to prevent tickets, but it is better to keep our releases leaner as well, so lets do in 6.0 itself.

**Comment by himeshr** [comment]
## Issue debug notes

### Bug fix
The issue reported on prerelease was not reproducible as the db has been refreshed.
Inspite of this, one issue was apparent, 
- we were allowed to register a "Female" Individual as a "Wife" for another "Female" Individual
- similarly, we were allowed to register a "Male" Individual as a "Husband" for another "Male" Individual
Though this isn't allowed as per the RelationshipTypes definition.

To resolve this, code changes were done as seen in commit, [391ac42](https://github.com/avniproject/avni-client/commit/391ac42fe3a551c9312b586bce8810c49719c566)

---------------------------------
### Hermes compiler switch forced change
Additionally, during testing, found that the app would crash, whenever we were entering the error scenario during save of AddMember action. This was caused due to switch to Hermes compiler from JSC, which is not able to handle the Error Stacktrace parsing during log.

To resolve this, had to make code changes seen in [53cf811](https://github.com/avniproject/avni-client/commit/53cf81194de8fca5fbaa78f18133d2fd458f0158) commit.

---------------------------------

**Comment by mahalakshme** [comment]
Just updating whatever discussed. Non-applicable relationships should not have displayed. But we can deal this in separate card, since not a priority.
