### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1132]
### Setup:

To use the below queries, make prerelease-db(has backup of prod data with below duplicate image urls) as the prereleasedb and delete the old one. 

### Analysis:
While trying to look at the image viewer, we noticed that there are about 680 duplicate images in the gdgsgom organisation.

select uuid, image_url, concept_name, count(*) from gdgsgom.media
group by uuid, image_url, concept_name
having count(*) > 1;

You will notice that these are not just duplicate in the media table, but within the individual observations. Try looking at the individual observations.

select observations -> '33bfd120-e0c1-4d3a-abd5-54bef7795b1d'
from individual
where uuid = 'b8644140-1d66-43aa-ae9d-b9d8ed4b8ce1';
[
"https://s3.ap-south-1.amazonaws.com/prod-user-media/gdgsgom/3dfaa1d1-26ea-496b-8bf0-abc57fd477f8.jpg", 
"https://s3.ap-south-1.amazonaws.com/prod-user-media/gdgsgom/ab29174f-8820-485d-87c0-92e69b2f05ce.jpg", 
"https://s3.ap-south-1.amazonaws.com/prod-user-media/gdgsgom/3dfaa1d1-26ea-496b-8bf0-abc57fd477f8.jpg", 
"https://s3.ap-south-1.amazonaws.com/prod-user-media/gdgsgom/ab29174f-8820-485d-87c0-92e69b2f05ce.jpg"
]

Notice that the second and fourth images are the same.

This is not because the image was uploaded twice (that will show up as different uuids)

- specific to gdgsgom and not other RWB orgs. It is probably a configuration/rules problem, or some one-time data script. 
- not happening always with gdgsgom as well

#### Analysis:
- On a higher level analysis of the code, unable to find any issue with pushing of media observations. Need debugging to confirm the same.

#### Acceptance criteria:

- Identify the root-cause for the duplicates.

**Comment by 1t5j0y** [comment]
Findings:
1. Also noticed duplicates in prod in the media tables for goonj, rwb2023 and rwbniti. (Not comprehensive list. Just ruling out that this is a gdgsgom only issue.)
2. In most duplicate cases, seeing multiple versions of the same file on S3 (pointing to an issue on the client generating the same uuid for multiple requests somehow). Also noticed multiple sequential calls to `GET /media/uploadUrl/` for the same uuid in the logs for some recent occurrences.
3. Doesn't seem to be tied to duplicate syncs - Found occurrences of duplicate images when there was no duplicate/parallel sync. 

Continuing to debug.

**Comment by vinayvenu** [comment]
@1t5j0y just confirming, if you are looking into ETL code, this is not an ETL issue. The root cause is that there are duplicate urls in the observations where this is coming from. 

Also, satbara document has 16k entries with 20% duplicates while "Log book image 1" has 7k rows but not that many duplicates. 

```
select concept_name, count(*)
from gdgsgom.media
group by concept_name order by count(*) desc limit 5;
concept_name | count
If the landholding is less than 2.5 acres, then uplaod satbara document | 16605
Log book image 1 | 7222
Image 1 of the site | 789
Video of Site | 789
Image 2 of the site | 684



select concept_name, count(*)from
(select concept_name, image_url, count(*)
from gdgsgom.media
group by concept_name, image_url
having count(*) > 1) a
group by concept_name;

concept_name | count
If the landholding is less than 2.5 acres, then uplaod satbara document | 687
Image of MB recording | 4
Please upload post work measurements image | 2
```

**Comment by 1t5j0y** [comment]
Noticed a separate issue while testing this card and created #1144

**Comment by 1t5j0y** [comment]
Root cause for the duplicates is parallel manual and automatic sync.

Easier to simulate when there are multiple media items to upload, the media items are large and over a slower connection.

**One way to simulate:**
1. Save a form that has media form elements
2. Perform any action that would take the Avni app out of the device's working memory (force close Avni / open up other apps)
3. Relaunch Avni - This would cause the automatic upload sync to trigger
4. While the automatic upload sync is going on, tap on the sync button (users might do this too since the icon shows unsynced items)
5. The parallel syncs interfere with each other by starting off uploads of media items which are still in progress by the other sync and this results in the dupe observations.

**Video to demonstrate:**
https://drive.google.com/file/d/1rQ6D5jz14pW5yxAcFQKI9-W3CNcHlt8H/view?usp=share_link

Observation answer for the media form element after the above sync in the realm db was:
```
{"answer":[
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/62ce2cef-f983-4899-ad6d-2848fcf3a02f.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/a317c196-0023-4fa8-95f2-a3620d690c36.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/c6def907-ce4a-4461-85a0-7f5b60c90eeb.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/516b1dc3-4c76-4b8c-8649-d38525e3e528.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/c6def907-ce4a-4461-85a0-7f5b60c90eeb.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/cfd886ee-069a-424d-b013-fb1993285862.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/a317c196-0023-4fa8-95f2-a3620d690c36.jpg",
"https://s3.ap-south-1.amazonaws.com/prerelease-user-media/gdgsgom/cfd886ee-069a-424d-b013-fb1993285862.jpg"
]}
```

**Comment by mahalakshme** [comment]
@1t5j0y Vinay suggested fixing the data as well by us. Hence moving this card back to Ready. Not only in gdgsgom, we need to fix the duplicate images across orgs.

**Comment by 1t5j0y** [comment]
@mahalakshme @vinayvenu Unassigned myself so anyone can pick it up. Don't we need to fix the duplicate syncs issue first to prevent occurrences of the issue?
