### ISSUE TITLE
Sort program names alphabetically

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1189]
### Motivation
When there are quite a few programs in an organisation with long names, it becomes hard to identify and choose the right program. The two issues currently include
1. Ability to see program names well
2. Ability to get to the right program easily

### Acceptance Criteria
As a user, when I press on "Enrol into Program", then the list of eligible programs are sorted alphabetically and visible well. This should be workable when there are upto 40 programs.

**Comment by 1t5j0y** [comment]
Moving to QA ready without code changes since the programs are [already sorted by display name](https://github.com/avniproject/avni-client/blob/9c15820f201228e93eb4748800845eea2521bf7e/packages/openchs-android/src/action/individual/IndividualProfileActions.js#L44) and display the entire program name.

Current sorting doesn't handle upper/lower case but we don't have programs named with lower case.

[Screenshot](https://github.com/avniproject/avni-client/assets/54208632/79aed141-8108-4b3f-9889-320691336271)
