### ISSUE TITLE
Continuing minor mismatch in WFA zscore

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1285]
https://avni.freshdesk.com/a/tickets/3216

### Context:
As part of [this](https://github.com/avniproject/avni-client/issues/1217) and [this](https://github.com/avniproject/data-fixes/issues/1) card, zscore calculation was corrected for new and existing data for the org in focus. But client have raised below 2 issues that were already addressed as part of the above 2 cards:
- There is still minor mismatch of the WFA zscore values - refer the spreadsheet in the ticket. 
- Not all the WFA zsore values shows with 2 decimal places,

### Analysis:
1) As shared by the client in [this](https://docs.google.com/spreadsheets/d/1xWIFjbg6FFBOsXzmUl4YVYuqH_mrXeEK/edit?usp=drive_link&ouid=106283016872857680393&rtpof=true&sd=true) sheet, WFA first z-scores for individual with ids 367809, and 1301382 have minor difference with that of the WHO's anthropomentry app.

for id 1301382

![Image](https://github.com/avniproject/avni-client/assets/10369963/f73e0d24-7d10-4f19-9774-9792c8d0c39a)

for id 367809

![Image](https://github.com/avniproject/avni-client/assets/10369963/9260a34c-e78c-447d-a756-4c0b2eb3ba87)

2) For program encounter with id, 2730765, the script for updating WFA zscore is not even run(no update in manual_update_history column). 

```
select individual.id, individual.gender_id, program_encounter.observations, individual.date_of_birth, program_encounter.encounter_date_time, program_encounter.manual_update_history from program_encounter join individual on program_encounter.individual_id = individual.id where program_encounter.id=2730765 and program_encounter.name='Growth Monitoring Visit' order by encounter_date_time desc; 
```

### Acceptance criteria:
- Address the minor mismatch in WFA zscore in both places(avni-health-modules code, update script for existing values) if exists
- Make sure script update runs for all program encounters for the existing values for the org in focus
- Looks like in the places we have with single precision, its because the next decimal no is zero. But -3.40 is considered to be higher precision than -3.4. Hence make sure all WFA values have double precision.

**Comment by petmongrels** [comment]
- the zScores have been updated by the script and the numbers are also matching the new logic
- regarding mismatch using fractional age doesn't help because the zScore value swings to the other side that is -4.47 goes to -4.56 for WHO score -4.53. Sometimes it swings by the same amount so it is not getting closer to WHO number.
- from the data where the mismatch has been highlighted it seems that these are all -3 to 3 and we we do not have any adjustment for SD below -3 and +3
- not sure what can be done in this case to make the data better

**Comment by vinayvenu** [comment]
A few observations
1. Our code is based on algorithms and data provided in https://www.who.int/tools/child-growth-standards . 
2. This issue is raised about mismatch from this and an anthro software provided by WHO whose source is not open to be inspected

In this scenario, the only way we can verify correctness is by verifying against the standard itself. 

I have provided an open calculation on the spreadsheet. Mistakes can be pointed out either on the data (if it does not match the open standards) or on the algorithm (provided on the spreadsheet), not on another software blackbox. Based on these calculations, the zScore in Avni seems correct. 

cc @mahalakshme

**Comment by mahalakshme** [comment]
@vinayvenu where is the spreadsheet?

**Comment by vinayvenu** [comment]
Updated the spreadsheet that you have in the card description
