### ISSUE TITLE
App is getting crashed

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1294]
When we try to register the subject the app is getting crashed 

org : rwb24uat,rwb2023
env : per-release
apk : https://app.circleci.com/pipelines/github/avniproject/avni-client/2301/workflows/19833411-fed4-4d4b-8ece-d4775b86a708/jobs/14296/artifacts
user name : dineshg@rwb2023
user name : dinesh@rwb24uat

Steps to reproduce : 
1.Login to the org 
2.click on the register 
3.register the farmer 
4.Click on the save and register another

Expected result : app should save the farmer
Actual result : app is getting crashed 

https://github.com/avniproject/avni-client/assets/127730126/fb70ad3c-719a-43d4-a1c7-e9b674fa78f9

**Comment by himeshr** [comment]
Issue was caused due to missing AddressLevel.locationProperties data while saving Individuals for organisations with EmbeddedObservation for AddressLevels. Orgs like Goonj or RWB*.

## Test cases to validate:
- For organisations **with** Location properties set for Address-Levels (Goonj, RWB orgs)
    - Create Subject
    - Edit Subject's address
- For organisations **without** Location properties set for Address-Levels (JSS and most other orgs) Regression
    - Create Subject
    - Edit Subject's address

**Comment by himeshr** [comment]
Changes are done in registration of Individual of types:
- Person
- Subject
- Family

@Dinesh2019 test these cases during validation.
