### ISSUE TITLE
Unable To See Draft Encounter/subject

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1321]
**Describe the bug**
Currently unable to see draft encounter/draft subject.

**To Reproduce**
Steps to reproduce the behaviour:
1. login in avni-client with user of org Collectives for Integrated Livelihood Initiatives (UAT)
2. try to do encounter 
3. go to subject 
4. there is no draft encounter.

**Expected behaviour**
Draft save should work with subject/encounter/program encounter save
https://avni.freshdesk.com/a/tickets/3577 - Also make sure the issue raised in this ticket would not occur 

**Smartphone (please complete the following information):**
avni-client 6.1

https://github.com/avniproject/avni-client/assets/106894932/5b531db5-ee24-4a6a-9ce8-6d316398e04d

**Comment by himeshr** [comment]
In general Draft's do not get saved, unless there are no validation errors in the form, when the "Next" button is clicked.
In the case of screen-recording attached here, there seems to not be an issue shown on screen but the date of encounter is before the subjectRegistrationDate, which should have thrown a validation error.

We have been able to create drafts for other encounterTypes in this and other organisations successfully, when there are no validation errors.

**Comment by himeshr** [comment]
@Dinesh2019 please reproduce with an org, without having the mobile system date time out of sync from network time.

**Comment by Dinesh2019** [comment]
The draft feature is not behaving as expected for encounters. When we started filling the encounter and came out of the page the draft encounter is saved and should displayed after or before the visit planned as that user can easy find the encounter which are saved as draft.

env : prod 
org : cini
User : dinesh@cini_uat

Steps to Reproduce :

1.Login to the org
2.go the search page
3.Search of the activity
4.start filling the activity encounter Note : at least first page should be completed to save it as draft
5.click on the page again go the activity

expected : draft should be saved and displayed separately
actual : draft getting saved but not displayed separately

Video References :




https://github.com/avniproject/avni-client/assets/127730126/57504347-54bf-41d4-9af3-5eb0c3cad66f

**Comment by 1t5j0y** [comment]
@Dinesh2019 this is as expected. Only unscheduled encounters are shown as drafts.

**Comment by 1t5j0y** [comment]
Issue is only if user exits encounter via the back button. Home button -> search for subject -> go back to subject was showing the drafts. 

Root cause: Draft was being saved but state was not being refreshed on back from the encounter.

Updated https://avni.readme.io/docs/draft-save to reflect current behaviour about display of unscheduled/scheduled encounter drafts

**Comment by Dinesh2019** [comment]
If I begin an unscheduled encounter but exit without completing it, saving it as a draft, and then proceed to start a scheduled encounter before finishing the unscheduled one, will the unscheduled encounter draft remain under the draft section, or will it be removed because I initiated the scheduled encounter?



https://github.com/avniproject/avni-client/assets/127730126/c8511dc8-a3fb-43ea-ab47-588595f9a1a6

**Comment by AchalaBelokar** [comment]
- [x] Tested on goonj for activity it was working fine there.
- [x] for genral encounter data saved but not separately like registration  
- [x] tested with schedule encounter
