### ISSUE TITLE
Type Cast error during sync of Distribution to Salesforce

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1353]
https://avni.freshdesk.com/a/tickets/3697

Wanted to add a card, since we know what is fixed as part of release, tickets are more for providing workarounds etc.,

**Comment by himeshr** [comment]
## Analysis
The goonj Distribution form considers the "Total Number of Families Reached" concept to be a Numeric Concept and its used in FormElement "Total Number of Families Reached", which is marked as a Mandatory field.

There are additional validation rule that this value cannot be zero.

For some reason, i see that User was able to insert a value of ".0" for this field and sync, which has resulted in this cast exception.

## Further action
- There is no issue to be fixed with the integration code, but rather a fix needed on the avni-client to avoid this sort of data issue in future.
- Also, make the correction in data for distribution with uuid "b056f016-ea8d-4539-8dc8-249719efba12" to have the value as 1 for this concept and allow sync to complete successfully.

**Comment by himeshr** [comment]
As part of dev-testing, confirmed that the value stored in observations for a input value of .012 would be numeric value 0.012 after this fix, which wasn't the case earlier. It was stored as string value ".012" before this fix.

**Comment by AchalaBelokar** [comment]
- [ ] checked with number and also checked whether it is reflected on db
