### ISSUE TITLE
BMI Value is not autocalculated

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1358]
We missed to tested the BMI and auto calculated values in the new version release 7.2.0 

env : prod
org : apfodishauat
user : dineshg@apfodishauat
apk: open testing

Steps to reporduce :

1.Login to the app 
2.Register the individual as female 
3.Enroll in the pregnancy program 
we have the form element BMI Value which is autocalculated from weight and height for the previous form 

expected result : BMI value is auto claculated
Actual result : BMI value is not calculated as expected 

https://github.com/avniproject/avni-client/assets/127730126/5854b3b3-1be9-4e08-897f-56fc6b5d5f97

**Comment by mahalakshme** [comment]
@1t5j0y looks like this is because of lodash  imports issue

<img width="1498" alt="Screenshot 2024-04-03 at 12 06 36 PM" src="https://github.com/avniproject/avni-client/assets/10369963/bc286591-02a0-4fa0-94d6-f509923a53d6">

**Comment by 1t5j0y** [comment]
@mahalakshme Confirmed issue is due to usage of _ in rule.

Fixed after replacing '_' with 'imports.lodash' in the rule.

**Comment by 1t5j0y** [comment]
Executed [script](https://gist.github.com/1t5j0y/94087957f8d5b761cc7b543eedaaa7d2) on prerelease to update usages in rules of lodash without using it from imports.

Entities for which rules have been updated are captured in [this sheet](https://docs.google.com/spreadsheets/d/1p378TgkMMztn2YoxLldU5Yz_Pn_eKq0rtzdhWckO8-k/edit#gid=0).

**Comment by mahalakshme** [comment]
@1t5j0y If not checked we might also need to check worklist updation rule, old rules

What will happen when there is no space around = in ```not like '% _ = imports.lodash%';```

**Comment by 1t5j0y** [comment]
Approach changed to find root cause of why lodash was not available in the rules.

Issue was due to avni-client referencing a commit hash on rules-config master branch (https://github.com/avniproject/rules-config/commit/279cdf88c979a4e50e7f1768449cec8f05e67500
) instead of the corresponding build branch commit (https://github.com/avniproject/rules-config/commit/982bb007c4f759639063159196edee386b48cac3
)

Restored prerelease db to a state before updates from previous comment were run to test this on prerelease.

**Comment by AchalaBelokar** [comment]
- [ ] Tested with Bmi with apf odisha
- [ ] And Rwb for total slit calculations
