### ISSUE TITLE
[RWB] After edited rejected work order to approval it is showing the json Parse error.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1389]
**Describe the bug**
[RWB] After edited rejected work order to approval it is showing the json Parse error.
After created work order I move the work order to the rejected and after that I edit the work order and try to approve it is is showing me the error.

**To Reproduce**
1. Login with beulah@rwbngos2023
2. create a work order
3. reject that work order
4. click on rejected
5. edit that work order
6. approve the work order
7. see the error

**Expected behavior**
error msg should not show

**Screenshots**
If applicable, add screenshots to help explain your proble

https://github.com/avniproject/avni-client/assets/104890488/10a9dffe-40b3-47bc-adc8-b3d185081096

**Comment by mahalakshme** [comment]
check if it happens in the branch released to RWB

**Comment by himeshr** [comment]
Unable to reproduce issue on Avni app, 8.0 release apk on prerelease env for beulah 2023 user

**Comment by himeshr** [comment]
Able to reproduce this issue, which has the root cause same as #1405.

Steps to reproduce:
1. Install avni apk without fix for #1405 
2. Use user that has fast-sync setup of version less than 188
3. Start the app
4. Navigate to subject Register screen and attempt to create a work-order
 OR
    Navigate to Reject / Pending Approvals CustomReportCards and try to check details of Subject.



https://github.com/avniproject/avni-client/assets/72493481/c31bc943-6708-46e6-a701-7137acf37e09

**Comment by himeshr** [comment]
Duplicate of #1405
