### ISSUE TITLE
UI/UX changes for showcase

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1402]
Issues:
https://drive.google.com/file/d/1Qu-jvYeHgBpsaqOGesa_4Jxb87k_oUT8/view?usp=sharing - Video that has issues pointed out

- Program enrolment audit details need to display in the `Enrolment details` section not in the `Summary` section
- Need to change the format(Enrolled on 12 Nov 2023 by Suresh) of audit as in the [mockups](https://drive.google.com/file/d/1V4u4tlpR0o-9Ni567vapnx2sSyVD4233/view?usp=sharing). Same for registeration details in Profile tab as well.
- On clicking edit of Enrolment details, top bar that has the name is white in color and hence not visible - change the name to black
- Summary table of Enrolment looks separate, it also needs to have grey background like we have for encounter table so that it looks as one unit
- When the beneficiary has not enrolled in any program we show some gray bg  unnecessarily
- There is some grey footer unnecessarily
- Relative box seems to be too bigger, move the DELETE button somewhat closer to other details
- When clicking on Menu -> dashboard, the filter icon should not be in the top right since the filters are not applicable for all dashboards, Hence it needs to display below the horizontal list of  dashboards we display and above the selected filters.
- The selected filters are displayed with grey bg in the [mockup](https://drive.google.com/file/d/1V4u4tlpR0o-9Ni567vapnx2sSyVD4233/view?usp=sharing). Currently we have blue bg, so the same can be done if it looks good.
- Currently there are different kinds of buttons which is somewhat looking wierd. So make all primary buttons like `Do`(on scheduled visits) similar to the one in [mockups(green button with white text)](https://drive.google.com/file/d/1V4u4tlpR0o-9Ni567vapnx2sSyVD4233/view?usp=sharing). Same for Edit, Enrol buttons as well
- Also on click of button we are showing grey border which also looks wierd. So, just replace it with [ripple](https://stackoverflow.com/questions/46234782/how-can-i-implement-circular-reveal-ripple-effect-when-user-clicks-on-a-cardview) effect.

**Comment by petmongrels** [comment]
Please verify colors in the app during code review review and QA.
For ripple the buttons are too small and transition too fast to see the ripple, but it looks better than displaying the border only like it was earlier.

**Comment by himeshr** [comment]
Have reviewed the code changes on github, looks good.

**Comment by mahalakshme** [comment]
It looks good. But found some minor improvements that can be made:
https://github.com/avniproject/avni-client/assets/10369963/28aa8414-ad7d-430c-9854-e44a0f49820e

- 'Enrolment details' and 'Visits planned' sections are not separated
- Secondary buttons like Exit, cancel we were displaying in red text before - it is good to do that or like it was in mockup(with dark grey) to distinguish it from primary buttons
- Since we have moved to flat design, it might be good to remove shadow for buttons as well like in the mockup
- Ripples are not visible for other buttons other than 'Enrol in ${program}'
- For design consistency good to keep the headers outside - hence can move the 'Summary' heading outside of the gray bg - thats how it was there before this card
- If possible we can do this: In the mockups for all buttons they have made the bg light, and text darker. Currently for the buttons not touched like 'New Program Visit', 'Scheduled' we are having darker bg and white color text. Since the overall theme in the mockups is based on using a lighter theme and colors for the app, we can do this if possible.

**Comment by mahalakshme** [comment]
@petmongrels I dont see any recent commit to check

**Comment by petmongrels** [comment]
### comments
- point 2, I have made the change but I am not able to make out whether the color is showing correctly or not visibly
- Have changed them to use TouchableNativeFeedback. I can verify on old style buttons, but in new style I cannot make out due to the colors used
- last one will have impact outside SubjectDashboard, so I have left it as it is

**Comment by mahalakshme** [comment]
@petmongrels 
- I see the primary and secondary buttons have the same color
- I checked for ripple in 'Add relative' button since it is bigger(similar size as 'Enrol in') and outside of gray bg - but it was not visible. 
- this is not needed for showcase: summary card is not of card structure

![Image](https://github.com/avniproject/avni-client/assets/10369963/178fcd39-c051-4a4c-b08d-185e49d2de8e)

**Comment by AchalaBelokar** [comment]
- [x] Program enrolment audit details need to display in the Enrolment details section not in the Summary section
- [x] Secondary buttons like Exit, cancel we were displaying in red text before - it is good to do that or like it was in mockup(with dark grey) to distinguish it from primary buttons
- [x] Since we have moved to flat design, it might be good to remove shadow for buttons as well like in the mockup
- [x] Ripples are not visible for other buttons other than 'Enrol in ${program}'
- [x] There is some grey footer unnecessarily
- [x] When clicking on Menu -> dashboard, the filter icon should not be in the top right since the filters are not applicable for all dashboards, Hence it needs to display below the horizontal list of dashboards we display and above the selected filte
- [ ] all senaro  are tested in the card
