### ISSUE TITLE
Missing media images

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1420]
https://avni.freshdesk.com/a/tickets/3932

### Need:
We see around for 1.5% of images(for goonj), we can find the URL in the db but the image is not present in S3. We expected [this](https://github.com/avniproject/avni-client/issues/1156) card would have fixed the media upload issue. But looks like more root causes might exist for missing media images.

### Analysis:
- Check [this](https://docs.google.com/spreadsheets/d/14n0Cij2St8p_OMYckws8nAqySZpSU_4saQP8YrxF180/edit#gid=616238170) sheet for the missing images in s3
- Take individual with id, 1582688 whose observations have missing images. The user who synced is in a version which has the above bug fix
- It doesn't seem to have happened because of media not existing in mobile since replacing of observations with URL has happened

### AC:
- Media should not go missing in s3

**Comment by mahalakshme** [comment]
@petmongrels can we try testing it, with slow network connection and more media and see if we can reproduce it. This: https://github.com/avniproject/avni-client/issues/1156 card seems to be tested .May be something similar we can try?

**Comment by petmongrels** [comment]
- We have had separate code for cancelling upload etc for slow connections. I am guessing we would have tested it at that time.
- I have reproduced the problem using wrong url in which case the upload fails now.

**Comment by 1t5j0y** [comment]
### QA Notes
If an error occurs after the url is replaced in the observation, the observation contains multiple entries for the same media item on retry of sync and subsequent success.

https://github.com/avniproject/avni-client/assets/54208632/af7d4e8d-e0b6-465e-aecc-881c36062268

Since we are only popping item from queue after url is updated in observation, an error here is unlikely and should not need a fix.
