### ISSUE TITLE
App crash when due date not saved for encounter

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1430]
https://avni.freshdesk.com/a/tickets/4174

### Analysis:
Currently for scheduled encounters(general or program) earliest_visit_date_time and max_visit_date_time can be null. There are no db constraints and this can happen when visit schedule rule is incorrectly(shelter - prerelease - visit schedule rule of `KAP-Survey Enrolment` form) written. This was not an issue until 7.3 but with adding of checks for encounters(to see if on edit visits scheduled is same as existing one) leads to app crash because of not sufficient checks added to handle when dates don't exist.

### Steps to reproduce:
prod, shelter
assign yourself the "KMC_Kalamba Filter House" catchment, turn off the internet and search for '0082' household subject_type, and try to complete 'Electricity' general encounter.

### AC:
- for the cases like above it should not fail for both general and program encounter
- if visits are scheduled without earliestVisitDateTime, record a rule failure and report via rule failure telemetry
- Add null checks in `datesAreSame` function to handle for the existing encounters saved without datetime fields.

### Long term fix: (not part of AC)
Such saving needs to be probably blocked from CSV, visit schedule rule and by adding deferred constraint in db (can be dealt in later releases)

**Comment by 1t5j0y** [comment]
AC updated in issue description after discussion of how this should be handled.

**Comment by mahalakshme** [comment]
@1t5j0y so you mean app will also not get crashed like now (say for the above case when saving electricity encounter) right? asking since app is not getting crashed currently when scheduling visits. Its happening when comparing datesAreSame with already scheduled visits which doesn't have datetime.

**Comment by 1t5j0y** [comment]
correct. Visit schedule rules returning visits without earliestVisitDateTime will fail and be reported to rule failure telemetry and not be scheduled so will not crash since they will not be checked via `datesAreSame`. A null check has been added to `toISTDate` (called by `datesAreSame`) where the original crash was happening just in case as well.

**Comment by mahalakshme** [comment]
@1t5j0y okay got it. the null checks will help for the existing encounters already scheduled wrongly and the rule failure will help for the future ones. so have appended the previous AC to the newly added ones.

**Comment by petmongrels** [comment]
### for QA
- rule editing is required for testing this
- we can test against the data we have for shelter in pre-release
- from rule we have to return null dates in different fields to test this

**Comment by AchalaBelokar** [comment]
- [ ] I Login with dinesh@shelter I register the household  after registration visits are not schedule it is happening on prerelease ..

Extract note : 

The issue is encounter not scheduled in the latest version 9.0

env : pre-release
org : ruletest
user : dinesh@ruletest
version 9.0 


https://github.com/avniproject/avni-client/assets/127730126/22ebcda1-ade9-4507-a2ea-060a504fcdda


Note : this is not happening in 8.1

env : pre-release
org : ruletest
user : dinesh@ruletest
version : 8.1




https://github.com/avniproject/avni-client/assets/127730126/9768007c-dd29-4b49-9492-514712d8743b

**Comment by Dinesh2019** [comment]
Scenario 1 : Unplanned visit 

if the visit is done as unplanned visit they the visit getting scheduled with earliest visit as null and it is not creating any rule failure 

Screenshot of the db: 



![Image](https://github.com/avniproject/avni-client/assets/127730126/61e602b7-32be-472e-9580-a2e29d6a9cd3)

screenshot of cilent app : 



![Image](https://github.com/avniproject/avni-client/assets/127730126/4a7293f3-72e5-41bf-9c4e-734d1ef74d44)



Scenario 2 : scheduled the encounter with earliestvisit date as Null

if complete the registration and the general encounter needs to scheduled but if the earliest visit date is null it is not scheduling the visit. And rule failure is capture as expected 


screenshot of webapp : 



![Image](https://github.com/avniproject/avni-client/assets/127730126/76749d05-58f7-4367-a7f1-fddc3472108c)


screenshot of cilent app : 



![Image](https://github.com/avniproject/avni-client/assets/127730126/a994a037-431c-4179-84f5-fd34ca38ed0e)

**Comment by 1t5j0y** [comment]
@Dinesh2019 @AchalaBelokar scenario 1 is working as expected since we performed an unscheduled visit in that case and did not schedule a visit. For an unscheduled visit, `earliestVisitDateTime` will be null.
