### ISSUE TITLE
Being able to apply all custom filters on 'Recent' type cards when part of custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1437]
### AC:
- Similar to https://github.com/avniproject/avni-client/issues/1382
- All the custom filters configured need to work with or without subject type filter added
- Example Expectations from different filters: seems to be working as below now and should not be broken: mentioned below only for those confusing ones
  - concept filter with encounter scope(bcoz concept present in encounter): 
        - registrations card: show individuals with concept in encounter set to selected value, registered within the recent duration 
        - enrolment card: show individuals with concept in encounter of the individual enrolments set to selected value, enrolled within the recent duration 
        - encounter card: show individuals with encounters completed in recent duration that has the encounter concept with selected value
  - program encounter date range filter:
    - registrations card: show registrations done in last 24 hours with any program encounters done within the filtered range
    - enrolment card: show enrolment done in last 24 hours with program encounters done within the filtered range
    - encounter card: show encounters done in last 24 hours with any program encounters done within the filtered range
   - similarly other filters including 'as on date' custom filter

**Comment by AchalaBelokar** [comment]
- [ ] Not able to edit the custom dashboard it is not allow me to edit that dashboard I login to maha@apfodisha and try to  edit the household dashboard. 

https://github.com/user-attachments/assets/72af697f-ff10-4913-ac8c-a362b30522f9

**Comment by himeshr** [comment]
While working on 10.0 client, encountering app crash due to clash in filters applied and the custom report card config.

[ClientErrorLogs.txt](https://github.com/user-attachments/files/16988803/ClientErrorLogs.txt)

Created new Dashboard filters of various types, as seen in
 https://prerelease.avniproject.org/#/appDesigner/dashboard/601/show 
<img width="1728" alt="Screenshot 2024-09-13 at 10 36 15 AM" src="https://github.com/user-attachments/assets/30bb6b78-170d-4a99-a747-ab6a621513b7">


Conflict due to Its filter with report card
https://prerelease.avniproject.org/#/appDesigner/reportCard/3002
<img width="1728" alt="Screenshot 2024-09-13 at 10 36 34 AM" src="https://github.com/user-attachments/assets/4ebc44d0-b076-42f9-9b9d-d84afe54cf3b">
