### ISSUE TITLE
[Dashboard] Disable auto refresh to be applicable on all dashboards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1452]
### As is:
Currently this auto refresh is applicable on only MyDashboard

### AC:
- When 'Dashboard Auto Refresh' setting is enabled for a user, all dashboards need to have its own refresh icon and last refreshed date. 
<img width="392" alt="Screenshot 2024-07-08 at 1 22 03 PM" src="https://github.com/avniproject/avni-client/assets/10369963/c8c190d9-02b3-47b4-bdbb-06c8a094cc49">

- Like shown in the image remove the pink message that says 'You may need to press refresh to get the latest counts' and instead of just 'Last updated on', display as 'Report card numbers last updated on'. This text need to be platform supported in different existing languages. 
- When refresh icon on a dashboard is clicked it needs to refresh counts of cards of that dashboard alone
- When a new card is added to the dashboard in webapp, and it's count is not yet cached, display 'Not yet calculated'
- When a card is removed from the dashboard in webapp, rendering dashboard should not error out

### Tech tasks:
- Unify DashboardCache and CustomDashboardCache realm tables - this is about storing new data of counts and filters, migration is separate card.
- Add cardJSON column for each custom dashboard as well in realm table

**Comment by petmongrels** [comment]
- When card is pressed the number of subjects shown may vary from the count shown, due to cache. So updating the count cache for the specific report card when the user does this.
- After sync the counts are not updated or cleared (sync can happen too often)
- Currently the dashboard on didFocus gives the impression that it is loading the data. Given that the data is cached, we don't need to do this on didFocus.

### development notes
Key events, conditional on auto refresh setting
- filter cleared (clear result cache, get aggregates)
- filter applied (clear result cache, get aggregates). Even if filter is applied without any change this would happen, not simple to do diff of previous and current filters
- sync completed (reset dashboards primary / secondary status, clear removed cards from cache)
- on dashboard load (get aggregates)
- on dashboard change (get aggregates)
- enable auto refresh (clear all dashboard result cache, get aggregates)
- disable auto refresh (get aggregates)
- force refresh (clear all dashboard result cache, get aggregates)

### tasks
- check for localised message on error (done)
- try to go to the same dashboard that is primary, via all dashboards. check results. (done)
- replace countUpdateTime with dashboard cache update time (done)
- saving of nested report card results to cache (done)
- on disable cache display of dashboard without any filters (can be done in display selected filters as styling will have to be changed again)

### problem with new card coming after sync
- it is complicating the logic too much. This is the first time scenario as well.

**Comment by petmongrels** [comment]
### QA, Bug Bash
- nested, non-nested
- auto refresh enabled/disabled
- new card added, removed and then sync
- exception in rule
- wrong number of nested items returned by nested rule
- standard report card or rule based report card
- filter applied
- filter cleared
- dashboard change
- force refresh
- presence / absence of cache
- filters with no value selected
