### ISSUE TITLE
Issue in offline dashboard location filter

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#1511]
**Describe the bug**
When there are villages with the same name in different Gram Panchayats (GPs), and we apply a filter based on the GP, individuals from both GPs are appearing in the card.

**To Reproduce**
1. Login to APF Odisha App as QRT user
2. Goto Filter
3. Select GP eg Badapalaspal
4. Click Apply
5. On the QRT Dashboard, click on Pregnant Women card
6. It should show only PW on Badapalaspa GP

**Expected behavior**
It should show only PW on Badapalaspa GP

**Screenshots**
[Screen recording](https://drive.google.com/open?id=1mn4wuvnmVtpxkZWlfkGophS9wT7ZKAVR)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
@sachsk Instead of name comparison, if we do uuid comparison it will work as expected

Report card query with issue:
<img width="1060" alt="Screenshot 2024-10-30 at 12 22 02 PM" src="https://github.com/user-attachments/assets/18f2ecb3-3837-4744-a143-5d32a7cd1179">

Fixed report card query:
<img width="1057" alt="Screenshot 2024-10-30 at 12 30 15 PM" src="https://github.com/user-attachments/assets/f0943b06-bca0-4923-a21d-a478f8e749bf">
