### ISSUE TITLE
Filtering by addresses when there are multiple hierarchies on a single device not working correctly

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1522]
We check for all descendants of selected addresses when filtering for standard report card types and even for custom report cards. Currently we are looking for descendants based on level number - this is incorrect. This should be restricted within the current hierarchy only. We need to also implement it such that when addresses from multiple hierarchies are selected then descendants in both hierarchies are included.

**Comment by mahalakshme** [comment]
### Issue:
On selecting Sector in Location filter, it still shows individuals registered in a Village in custom report cards.

### Analysis:
 I see it is working correctly in MyDashboard: https://drive.google.com/file/d/1fkQZlOlnDXbHCfkvn3uU-ERnrBubaRXZ/view?usp=drive_link

In custom dashboard it is not working because of the kind of query we have written. We are adding address filters that are of type only 'Village/Hamlet'. Else we are not adding. Eg report card: Total enrolments in pregnancy program in APF.
Video for that: https://github.com/user-attachments/assets/b446ffe8-37c8-47d0-bd0f-ea3de470cffe


cc: @petmongrels
