### ISSUE TITLE
Do not crash the application if rules fail on client side

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#181]
[Mobile client] User should be able to save form. Client doesn't crash on rule failure - all RuleTypes.
[Mobile client] Client should push the rule failures part of sync

Currently app crashes when we are pushing an answer concept to a decision but that answer concept is not there in device. Because the app crashes before saving the encounter, our users end up losing the data of encounter that they were filing. 

Data model
rule_failure_telemetry

    rule uuid
    individual uuid
    stacktrace
    user
    status [open, resolved]

**Comment by petmongrels** [comment]
Is there is a failure in skip logic then it would end up creating too many rulefailuretelemetry records. Because it is creating a record everytime it is getting invoked. For example if a form group as 10 form elements and one of the form element has error - and user fills that group, 10s of errors can be created on one page. If the user is using this form multiple times, lets say, for 100 beneficiaries in a week. Then there would > 1000 rulefailuretelemetry with exactly same information. This will uncessarily create noise and slow syncs.

**Comment by petmongrels** [comment]
The database there should be a column for datetime in rule_failure_telemetry table. We cannot simply depend on status to know whether an issue has been fixed before or not.

**Comment by petmongrels** [comment]
On successful sync rule failure telemetric is not getting deleted from the device. This is true with Sync telemetric also. Not sure what is the reason, just pointing it out.

**Comment by petmongrels** [comment]
For Program Enrolment Summary, if the rule is in health modules (not in implementation code) and if the rule throws error. Then the app crashes. Consequence the record itself cannot be opened.

**Comment by vindeolal** [comment]
1. Save failed rules only if RuleUUID, IndividualUUID and errorMessage differs.
2. Added new columns to rule_failure_telemetry (error_date_time, close_date_time, and audit_id).
3. On successful sync rule_failure_telemetry gets cleaned up on client.
4. Fixed the case of rule failure for program summary in Health Modules. In core we are directly calling the function for Enrolment Summary, hence when this rule fails it's rule_uuid is empty.
