### ISSUE TITLE
Respect subject passed from visit schedule rule

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#322]
[Concept Note](https://docs.google.com/document/d/1LT-1PT4bbCXRbKsL4VUplYVrQZyw1PiYD9HhxC_JgmU/edit?usp=sharing)

### Context
Currently, the visits are by default scheduled for the current subject. Now implementers will be able to specify the subject (along with encounter type, earliest visit date, max visit date). Avni client should schedule the visit for that specific subject. 

### Acceptance criteria
- [ ] Visit should be scheduled for the subject(s) returned from the rule. 
- [ ] Display this in S&R screen
- [ ] Save should not take more than 5 seconds for 50 members when a visit is planned for each. 

This feature could be used along with attendance recording. Lets say 20 members are present a particular form is to be scheduled on them. Or let's say 10 members are absent for more than 3 days then a particular visit is to be scheduled for them. 

### Tech
1. we should test the performance. If the perf is too bad, we would have to explore batching.

**Comment by 1t5j0y** [comment]
- [x] Get `subjectUUID` from rule (if present) and schedule visits across registration, encounter, ~enrolment, program encounter,~ (leveraging on existing `programEnrolment` parameter for enrolment/program encounter). 
- [x] If any subject UUID provided is not valid or corresponding subject is voided, log it to rule failure telemetry. Any other valid visit schedules from the same rule should be processed successfully.
- [x] Determine if `programEnrolment` parameter is scheduling a visit for another subject so these can be shown in the separate table on SR screen.
- [x] Review performance of load time of SR screen and form save  when multiple visits are being scheduled ~and introduce batching if required~. 
- [x] Update System Recommendations screen to introduce new table 'Visits scheduled for others' and display scheduled visits in this table. (Same as current visits scheduled table ~with addition of one column for Subject name~. Since there is no space for one more column, display a section for each subject with visits under them..)

- [ ] (Pending confirmation if required) Check for logged in user's visit scheduling privileges on the entity provided by the rule and ~show error~ log to rule failure telemetry if not present.
- [x] Dev box feedback: Support `programEnrolment` rule parameter for general encounters as well.

**Comment by 1t5j0y** [comment]
Moving to QA ready to test functionality as only UI improvements are pending.

APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-8684-2020-11-12-11-29-32.apk

[Sample rules](https://app.zenhub.com/files/64590403/bf4c25a3-5579-44ac-897e-b5d883eea2ec/download)

**Comment by 1t5j0y** [comment]
Included UI improvements and supporting scheduling program encounters using `programEnrolment` parameter from general encounters.

APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d901a-2020-11-16-16-57-37.apk
