### ISSUE TITLE
app crashes while editing enrolment 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#391]
**Describe the bug**
App crashes on editing an existing enrolment after updating a single select concept to multi select coded concept.

**To Reproduce**
1. Create an enrolment having a single select coded concept.
2. Complete the enrolment and save.
3. Make the single select concept as multi select and save the form
4. Sync app and try to edit previous enrolments.\
5. App crashes - **ReactNativeJS: TypeError: _this.props.multipleCodeValues.isAnswerAlreadyPresent is not a function. (In '_this.props.multipleCodeValues.isAnswerAlreadyPresent(answer)', '_this.props.multipleCodeValues.isAnswerAlreadyPresent' is undefined)**

**Expected behavior**
Ideally, updating concepts should not make Editing saved enrolments crash.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by arjunk** [comment]
this is a known issue. it happens because we have a different data structures to store single select and multi select. so effectively this can be considered similar to change of datatype. The data after changing from singleselect to multiselect or vice versa has to be migrated for the app to be able to understand it. Low priority at the moment considering the effort involved to fix this vs number of times this happens.

**Comment by vinayvenu** [comment]
Closing this as change in datatype is a lot more involved.
