### ISSUE TITLE
Set up Firebase analytics for Android app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#396]
### Introduction
Currently, we are not aware of usage patterns in our android application. This includes
1. Common navigation patterns
2. Time taken for different actions such as sync, search, move across screens etc, and contrasting with the amount of data on the device
3. Level of usage of features

A first list of things we want answers to are
1. Prevalence of use of MyDashboard as opposed to search for navigation
2. Prevalence of use of Filters in MyDashboard and SEARCH
3. Number of searches required to find what people are looking for
4. How often is the edit feature used
5. How many times people abort the form in between.

In order to get a better idea of these, it is useful to have analytics on the app. 

### Tech notes

- [x] Set up Firebase analytics on avni-client
- [x] Set up events for screen changes
- [x] Set up events for sync
- [x] Set up basic data to include organisation
- [x] Set up events related to the specific events mentioned in the requirements

**Comment by vindeolal** [comment]
Events take 24 hours to appear on the dashboard. There is debug view that can be used to check if events coming to the firebase. Use the below APK, and install it in the emulator. Next, run the below command from the terminal to turn on debugging so that events are sent on the realtime

`adb shell setprop debug.firebase.analytics.app com.openchsclient`

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4abac-2021-01-22-12-01-16.apk

DebugView link: https://console.firebase.google.com/project/avni-be4b7/analytics/app/android:com.openchsclient/debugview/~2F%3Ft%3D1611297320204&fpn%3D554603098537&swu%3D1&sgu%3D1&sus%3Dupgraded&params%3D_u..pageSize%253D25&cs%3Dapp.m.debugview.overview&g%3D1

Below is the list of events that are sent to firebase right now
```
sync_complete : When sync get completed
sync_failed : when sync fails
search_filter : when search button on the search screen is pressed
my_dashboard_filter : when apply button on the dashboard filter is pressed
edit_subject: when subject is edited
edit_encounter: when encounter is edited
edit_enrolment: when enrolment is edited
edit_program_encounter: when program encounter is edited
edit_enrolment_exit: when program exit is edited
abort_form: when user comes out of any from without saving it completely
```

**Comment by vinayvenu** [comment]
### Testing notes

- Sync complete takes time for ok button to be pressed, not time taken for actual sync. 
- sync failed - also worth putting time taken. 
- MyDashboardFilter - time taken only makes sense if we have the filters. maybe worth adding filters here
- Works in airplane mode or zero internet.

**Comment by vindeolal** [comment]
Feedback fixes

- [x] `sync_complete` event should be triggered when sync completes and not on the press of the Ok button.
- [x] `sync_failed` event should have `time_taken` parameter.
- [x] `my_dashboard_filter` should have `applied_filter` parameter. Same thing for `search_filter` as well.
- [x] There should be events for login and logout as well.

**Comment by vindeolal** [comment]
New staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-7721-2021-01-26-13-03-34.apk
