### ISSUE TITLE
Refresh the cognito token instead of throwing sync failed error.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#404]
Currently, we store the token in memory and use the same token throughout the sync, based on the number of pages for an entity, we build the ChainedRequestes list passing the same token (https://github.com/avniproject/avni-client/blob/d901afc2e996fb99742970985018305f795a58c6/packages/openchs-android/src/service/rest/ConventionalRestClient.js#L97). Since the token is valid for 1 hour, if the sync takes more than 1 hour then token get expired and the user gets sync error. This should not happen. 

**Tech approach,**
Retry mechanisms are fraught with failure, and should be done only if there are serious performance issues to be taken care of. Always refresh token for every call. This will add about 20ms per call, which should not seriously impact response times. 

**Testing notes**
- Impact areas (possible places of regression)
  - First time sync
  - Subsequent syncs
  - Realm backup and restore
  - Image and video syncs
  - SMS phone verification
  - Change password
  - Test long syncs taking more than an hour to ensure refresh takes place

**Comment by vinayvenu** [comment]
1. We should test other applications as the change you do will be at a filter level on the server. 
2. It might be more conventional to send server response as a 401 error instead of an exception. 
3. Avoid infinite retries (if the server fails the response a second time for some reason, we should not get into a loop trying to authenticate). 
4. Might be best to pass in authservice to conventionalrestclient, and let it handle the token lifecycle instead of remote controlling stuff from SyncService. Also call it refreshToken() and not getToken(). Of course, we should ensure it doesn't keep getting called everytime.
