### ISSUE TITLE
Ability to mark a field on the subject as unique. (on name or any field) as unique

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#442]
### Acceptance criteria

- I should be able to mark a subject type with name as "Unique Name"
- If a subject type has a unique name, then the android client should not be allowed to create another subject with the same name. 
- I should be able to mark a form field as unique. 
- If a form field is unique, then no other subject can have that value for values filled in as part of that form. 
- If another subject has that field, then show error "Another <subjecttype> has same value."

**Comment by vindeolal** [comment]
- Unique form field validation is only done for `Text`, `Numeric`, and `PhoneNumber` data types.
- Unique validation should be used with the regex, this is because of the way we store observations in the realm. Observation JSON is stored as a string and we need to perform contains a search for the value in observation.

**Testing tasks:**
- Test on the bigger dataset on the real device

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-14a3d-2021-03-26-12-17-03.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- If in a numeric field, no validation is there then it starts checking from the first digit. If the first digit is same then also give the error- "duplicate value"
Please check how it should work in this scenario.

**Comment by vindeolal** [comment]
@garimadosar5 as mentioned in the second point, 
- Unique validation should be used with the regex, this is because of the way we store observations in the realm. Observation JSON is stored as a string and we need to perform contains a search for the value in observation.
