### ISSUE TITLE
Sync taking 30 minutes even after using the dump

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#464]
**Describe the bug**
It is expected that if one is using a catchment dump then the sync should be incremental and not take very long. Something in the order of 5 minutes unless the dump is very old. In this case, the dump is from the same day.

**To Reproduce**
1. Use a device with fully synced data having lots of tx data
2. Setup fast sync
3. Reinstall the app
4. login with same user or another user in the same catchment (note that if you are creating a new user ensure that the identity assignment is set up correct, otherwise you may get app crash. bug reported for it already)

**Expected behavior**
The sync should use the restored dump and the incremental sync should not take around 5 minutes and not lets say 20 minutes.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
Not this bug but if previously testing was not done then it should be done

**Comment by petmongrels** [comment]
The fix was done in the mobile app code.

**Comment by garimadosar5** [comment]
Fix - 
1. When the app starts the first sync, it creates the DB and when restored DB gets download then that DB should get closed and the downloaded DB should start.
But created DB was not closing. Now that is fixed in this version.
2. If sync ends in-between then restart from where it left. earlier it did not consider the backup in this case. It starts with the normal sync.
3. If screen goes off in between then it get stuck at 87%. (download process ends at 87% and then unzip, restore starts).
