### ISSUE TITLE
Quick editing of a particular field of a form

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#547]
### Context
Many times, some fields are not available, and will need to be filled in whenever a form is filled in. It is necessary to be able to quickly jump to that area of the form. It is also necessary to save once you are done. 

Technically, every form element and form element group is evaluated whenever we move from that screen, which is the reason we have a "Previous" and "Next" on the form for moving. If we need to move quickly to a different screen, then the actions on each form element and form element group need to be performed. In case there is a problem, the form needs to go to that location to be fixed, and then move on. 

### Solution
1. On the form dashboard, we need a quick way to choose a specific field, and then move on to that field. This means we might need to increase space between rows on the "Observations" section to allow fingers to select a value to edit. 
2. From the screen where we edited that field, there needs to be an option to go to the end of the form. We can provide this in the form of a "Go to Summary" button on the top right (we do not want to modify the existing mechanism since a lot of people would be familiar to it). 

PS: We cannot just make a change inline in that form, because this mechanism can cause new visits to be triggered, and other form validations to kick in. 

### Acceptance criteria
- On all forms - registration, enrolment and encounters, additional headers will be provided for form element groups, where there will be an edit button. 
- On touch of the edit button app will move to the corresponding page
- On edit of the option, regular form save through Previous/Next will work

- On all form creation/edit, there will be a top button to "Go to Summary". This will keep going from one page to another, ensuring all validations are complete, and take user to the "Summary" screen. 
- If there is an error either in the same page, or any of the subsequent pages, app will take user to that screen with the error highlighted. 
- When moving, any values that need to be recalculated will be recalculated.

**Comment by vinayvenu** [comment]
### Context
Many times, some fields are not available, and will need to be filled in whenever a form is filled in. It is necessary to be able to quickly jump to that area of the form. It is also necessary to save once you are done. 

Technically, every form element and form element group is evaluated whenever we move from that screen, which is the reason we have a "Previous" and "Next" on the form for moving. If we need to move quickly to a different screen, then the actions on each form element and form element group need to be performed. In case there is a problem, the form needs to go to that location to be fixed, and then move on. 

### Solution
1. On the form dashboard, we need a quick way to choose a specific field, and then move on to that field. This means we might need to increase space between rows on the "Observations" section to allow fingers to select a value to edit. 
2. From the screen where we edited that field, there needs to be an option to go to the end of the form. We can provide this in the form of a "Go to Summary" button on the top right (we do not want to modify the existing mechanism since a lot of people would be familiar to it). 

PS: We cannot just make a change inline in that form, because this mechanism can cause new visits to be triggered, and other form validations to kick in. 

### Acceptance criteria
- On all forms - registration, enrolment and encounters, the text space will be increased, and an option will be provided to edit that field. 
- On touch of that option, app will move to the page where that element could be found. 
- On edit of the option, regular form save through Previous/Next will work

- On all form creation/edit, there will be a top button to "Go to Summary". This will keep going from one page to another, ensuring all validations are complete, and take user to the "Summary" screen. 
- If there is an error either in the same page, or any of the subsequent pages, app will take user to that screen with the error highlighted. 
- When moving, any values that need to be recalculated will be recalculated.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-9692c-2022-01-10-13-02-02.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Summary button is not working.
https://images.zenhubusercontent.com/64590403/99e9ec5e-d1eb-4920-bf82-f1babc616dfb/bug_1.mov

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-2c6c4-2022-01-13-10-48-55.apk
