### ISSUE TITLE
Fix autosync in the client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#580]
The sync source in sync_telemetry was introduced in avni-client version 3.17.4. 

**Problem 1**
Today, most of our syncs are not yet automatic although automatic syncs are expected to happen every 1 hour

#### Sync stats
> automatic    5342
> manual         70030
> null               10399

**Problem 2**
Also notice that a lot of syncs still have null as the sync source. This includes versions that are higher than 3.17.4 and up to 3.24.0. 

### Acceptance criteria
Identify the reasons for the above two problems, with the intention of fixing automatic syncs.

**Comment by vindeolal** [comment]
For the background sync not working the reason was Firebase JobDispatcher got deprecated after Android 10 and we have compile SDK version 30 (11). https://github.com/googlearchive/firebase-jobdispatcher-android

The library react-native-background-job provides two ways to schedule a job first is default and uses Firebase JobDispatcher and another one is exact which uses AlarmManager. Now Avni client background jobs are changed to use exact property.

**Comment by utkarshavni** [comment]
- Tested for Yenepoya organisation, on the emulator and Device.  Records updated in the app were not visible after more than an hour through search in DEA. The sync_telemetry table also does not have any entries in sync source for Auto-sync. (Yenepoya_staging DB).

**Comment by vindeolal** [comment]
Moving this to on hold, and picking other priority tasks. We need to do more analysis and test the solution properly. Currently with the changes done it works on some devices and does not work on some.

**Comment by vinayvenu** [comment]
Closing this task as duplicate of https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-client/447
