### ISSUE TITLE
Location form element does not show value during edit

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#685]
Location form element doesnot show selected value during edit of an encounter
I'm able to navigate to next screen, and the location is shown correctly in the Summary page before save of the Encounter.
So its just that the value isn't being displayed.

To reproduce
Goonj organisation. Try editing a distribution that you filled in once.

**Comment by himeshr** [comment]
This issue was caused due to missing location entries in local avni-client db. The fast-sync file contains lesser entries that the number of locations uploaded for Maharashtra.[https://app.zenhub.com/files/64590403/fd274a07-ba88-42dc-8b6a-7caa25dcf4be/download](https://app.zenhub.com/files/64590403/fd274a07-ba88-42dc-8b6a-7caa25dcf4be/download)

**Comment by himeshr** [comment]
on debug, found that the issue was caused due to data issue. There were few entries in the local mobile database that did not have any locationMapping specified linking an addressLevel with its parent lineage.
This would result in error during display of AddressLevels, as they would also be considered as candidates as Root levels.
![Screenshot 2022-09-26 at 6.50.12 PM.png]
(https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/0d4d72b8-7d77-4adf-a7d6-2f64c2b8cd1f)

In-order to overcome this solution, the fix was to update the addressLevel and location_location_mapping entries for the affected entries.

update address_level al set last_modified_date_time = now() where al.uuid in ('0fbc92ce-d0ea-4928-a615-732bcfb6134c',
                                                                              '680a0ea7-7d0b-4cac-96d7-38210dd96584',
                                                                              '90b09335-daa8-47bb-82db-d6abfcdb8c88',
                                                                              '64f342b2-2399-4006-9162-4d4f5a43f4b2',
                                                                              '6f5d668d-4a48-4d72-b3bb-5f3568d4a40d',
                                                                              'f3554b23-5082-48da-a5e8-41f1919bcc61',
                                                                              '72c819c4-c274-48d4-9f67-9efb37fcfba4',
                                                                              'f691fb34-b04f-4a19-957e-dde937f9bcfa');

update location_location_mapping llm
set last_modified_date_time = now()
where llm.id in (select location_location_mapping.id from location_location_mapping
                                   left join address_level al on location_location_mapping.location_id = al.id
                 where al.uuid in ('0fbc92ce-d0ea-4928-a615-732bcfb6134c',
                                   '680a0ea7-7d0b-4cac-96d7-38210dd96584',
                                   '90b09335-daa8-47bb-82db-d6abfcdb8c88',
                                   '64f342b2-2399-4006-9162-4d4f5a43f4b2',
                                   '6f5d668d-4a48-4d72-b3bb-5f3568d4a40d',
                                   'f3554b23-5082-48da-a5e8-41f1919bcc61',
                                   '72c819c4-c274-48d4-9f67-9efb37fcfba4',
                                   'f691fb34-b04f-4a19-957e-dde937f9bcfa'));

**Comment by himeshr** [comment]
For Goonj UAT implementation, this issue was present only for 'Assam-Andhra pradesh' catchment, which was corrected after running commands specified below. Post that catchment fast-sync was retriggered and validation of the realm file within the fastSync uploaded file was also done.
Commands to correct issue:
----------------------------
update location_location_mapping llm
set last_modified_date_time = now()
where llm.id in (select location_location_mapping.id from location_location_mapping
                                                              left join address_level al on location_location_mapping.location_id = al.id
                 where al.uuid in ('39945b0e-88e1-4bfd-a6a0-7ce4a6103a49'));

update address_level al set last_modified_date_time = now() where al.uuid in ('39945b0e-88e1-4bfd-a6a0-7ce4a6103a49');

**Comment by AchalaBelokar** [comment]
In prod taqi@guat edit location is not working.
