### ISSUE TITLE
[RWB] Rule fails for specific users

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#686]
Rule failure -
null is not an object (evaluating 'enc.latestEntityApprovalStatus.approvalStatus')
( 222 rows till now)

Rule is -
const calculateSumOfObservationValues = function(encounterTypeName, observationName) {          
        return encounter.individual.getEncounters()
          .filter((enc) => enc.encounterType.name === encounterTypeName )
          .filter((enc) => enc.latestEntityApprovalStatus.approvalStatus.status === 'Approved' )
          .map((enc) => parseInt(enc.getObservationReadableValue(observationName)))
          .reduce((total, val) => total + val, 0);
    }
  

The above rule or similar rules where the latest entity approval status is being fetched is failing for specific users only  while the rule works fine for other users in the same group.

Working fine for user -penparam_vss@rwbrj
While the rule is failing for - manoj_vss@rwbrj

Also, there are no encounters/entity without approval status in DB.

**Comment by petmongrels** [comment]
The issue is:
- The user has a dump
- The dump has 6 encounters with the latest approval status as null (all other enc has the approval status)
- sync post-dump restore also, doesn't fix these encounters

It is difficult to tell how/why this issue happened. Ideally, the sync after dump restore should find the approval status but it doesn't.

On fresh sync, the issue doesn't happen. So that is the fix.
I have renamed the dump.

The implementation of approval status sync is problematic and difficult to reason about for such scenarios, which is a bigger change that needs to be handled in the platform.

In future, if such issues happen, it may be difficult to tell without analysing the db (which I did using the Playground app available in avni client).

**Comment by nupoorkhandelwal** [comment]
Its fixed for the specified user, @arjunk @petmongrels What about the remaining 96 users for whom the rule is failing?
https://docs.google.com/spreadsheets/d/11toI_l6gQnptJKxe196RsSiYj8V2qqpbCHv-vx6UEtI/edit#gid=0

Should I share this list and ask them to do a fresh sync?

**Comment by nupoorkhandelwal** [comment]
Its fixed for the specified user, @arjunk @petmongrels What about the remaining 96 users for whom the rule is failing?
https://docs.google.com/spreadsheets/d/11toI_l6gQnptJKxe196RsSiYj8V2qqpbCHv-vx6UEtI/edit#gid=0

**Comment by petmongrels** [comment]
@nupoorkhandelwal @arjunk 
Considering everything the best option will be for them to do a new sync after pushing their local changes. We will also need to remove/rename the uploaded DB dumps for these catchments from S3. The sync will take some time but compared to the options available this is still the fastest way.

The other options are complicated and there is no guarantee that they may fix the issue for everyone. Given the number of users, the coordination required may be too much for us.
