### ISSUE TITLE
Unable to go to the next page even though all the mandatory fields have been filled

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#751]
https://images.zenhubusercontent.com/64590403/36ba089d-993b-4390-a46c-680b3e06b733/screencast_from_29_11_22_07_44_50_pm_ist.mp4

**Comment by vinayvenu** [comment]
Cannot reproduce this issue.

**Comment by AchalaBelokar** [comment]
Orgnization : sakhi app on prod ..
Utakarsh  and taqi have more context about it

**Comment by vinayvenu** [comment]
This was fixed by changing the rule. 

Date of marriage field was trying to figure out the ageAtMarriage, and throwing a validation error. This was not being displayed because it was also not visible on the screen. 

There is a related product issue where validation errors are being shown when the field is not visible. This will be tracked in a different card.
