### ISSUE TITLE
Home page menu items should be usable even if the dashboard cards are loading

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#762]
Custom dashboards are written specific for implementations, and Avni cannot guarantee the performance of these cards. However, the rest of the application should still be accessible even if these cards take time to render. 

We can achieve this by running renders through a background job, and ensuring that the spinner does not interfere with the buttons. 

### Acceptance criteria
- Ensure app is working for regular dashboards
- Ensure app is working for custom dashboards

### Tech tasks
- Send calculation to a background job
- Cancel the background job if user navigates to a different screen
- Ensure spinners do not interfere with the actions on the home screen or on other screens

**Comment by petmongrels** [comment]
From the user's standpoint.
- If the reports are fast to run then it makes sense for them to be updated all the time.
- If they are slow then run them as optimally as possible and show them the counts. It is important to note that if the counts are slow to run then pressing the icon will also be slow.

About the reports
- The performance of the reports is variable depending of the database size and queries. Some reports may even take up to a minute to execute.

About background job
- Cancelling a background job stops future execution of the job. If the job is currently running then it will not be killed. It will be sent a signal.


Solution 1
------
- Fire a background job whenever the user comes to the dashboard with an indication that the reports are running
- If the user moves away then kill the background job

This has the following issues
- Killing an instance of background job is not straightforward. The background job code has to keep checking for signals and then aborting. Even if the background job code does this, if it is stuck in IO then nothing can be done than wait for it to complete execution and then abort. When the report is running the app will be quite slow. Even the user's intention to step away from the dashboard may take a while to respond.
- The smaller issue is having to write code in Dashboard control in several places to fire abort. Maybe a lifecycle method in react could be utilized to do it in one place.

Pro: The numbers are updated always for the user.

Solution 2
------
Run the report in the background always and give the user a manual refresh button. If the user manually refreshes then the user has to wait for the reports to run fully before they can use the screen. If the background job is already running, show the indicator to use on the dashboard.

Issues
- the numbers will be out of sync with DB
- when the background job is running the app will still be slow depending on the data etc

Pro: The app's performance impact from reports can be controlled by adjusting the frequency of background report jobs. The code is slightly simpler to maintain compared to solution 1.

**Comment by vinayvenu** [comment]
In Solution 2, one big issue is the behaviour change for users who are used to seeing dashboard changes after every change. 
eg - In many implementations, users are given targets for a day, and they continuously keep checking how much of their task list is complete. There will be a settling down phase where we should expect more support tickets to be raised (and potential frustration associated with it). 

Also, even with Solution 2, we will need to cancel a running job when someone presses the refresh button (chance of this happening depends on the time taken to render the dashboard, and the frequency of people trying to refresh it. It can potentially be a normal scenario for some users).

**Comment by vinayvenu** [comment]
#### Conversation from Skype

**Arjun**
I think we can consider a hybrid approach. In other words, refresh strategy at the card level. Certain cards like Due, Overdue, Registration count are required to be auto-refresh and my assumption is they are not performance intensive. The other cards can be on manual refresh which will be triggered by dashboard refresh.

Also, we should explore if we can provide a way to base multiple dashboard cards on single report query. e.g. fetching all uncompleted visits grouped by due and overdue and then rendering in different cards may be faster than each card going to the database.

this involves complexity at both product engineering and implementer level but i don't see an easy way out.  

this similar approach we would need on canned analytics also. 


**Vivek** 
I also think making more granular cards with their own configuration related to refresh is good idea.


Infact we don't need any background thing this way. Each card is either auto refresh or manual. We could give manual refresh all.

If it is fast=we refresh. If slow you refresh


**Vinay**
Multiple cards *may* let people see some information beforehand. It can also make the screen slightly more responsive (you can sneak in a UI action between two card renders). However, if you want to prioritize app usability during card renders, we will still need to run in background because even individual card renders can get slow.

**Comment by vinayvenu** [comment]
After more discussions, a new epic has been created [here](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-product/1296). Closing this card.
