### ISSUE TITLE
(LAHI) MagicB Eligibility is not auto populated  in staging  web app

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#766]
MagicB Eligibility is not auto populated  in staging rest are working fine
 ![Screenshot 2022-12-16 at 6.22.40 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d32ef232-bede-4034-946c-bb5fef083b11)

**Comment by himeshr** [comment]
The issue was caused due to in-complete rule, specification, which did not cover all cases.
After correcting the rule, we are now able to see MagicB eligibility having correct value.
![Screenshot 2022-12-20 at 6.18.49 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/83776a26-d434-4ffa-9c0c-b2ed528d1da5)
Missing condition, which we have now added is shown in screenshot below:
![Screenshot 2022-12-20 at 6.20.42 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/dcfc2fdf-b7de-4b8a-a655-3c010a56eed0)

**Comment by himeshr** [comment]
The issue was caused due to in-complete rule, specification, which did not cover all cases.
After correcting the rule, we are now able to see MagicB eligibility having correct value.
![Screenshot 2022-12-20 at 6.18.49 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/83776a26-d434-4ffa-9c0c-b2ed528d1da5)
Missing condition, which we have now added is shown in screenshot below:
![Screenshot 2022-12-20 at 6.20.42 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/dcfc2fdf-b7de-4b8a-a655-3c010a56eed0)
