### ISSUE TITLE
[avni-client] AWC profile subjects not syncing to APF users on prod

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#794]
Currently, when a user does fresh sync all the AWC profile subject registered doesnt get synced to the users device.

For test use

Name- Chhabirani Sahoo
User Id- 9692117164@apfodisha /password

**Comment by vinayvenu** [comment]
Deployed as part of 3.35.4

**Comment by himeshr** [comment]
Performance testing Benchmarking info:

Single sync details request:
---------------------------
Before code change| With spring cache| Without any caching
~ 4 seconds| ~ 3 seconds| ~ 5 seconds

Same request invoked 10 times in parallel:
------------------------------------------
Before code change | With spring cache| Without any caching
~ 30 seconds | ~ 10 seconds| ~ 60 seconds

**Comment by petmongrels** [comment]
the default TTL value is optimized for memory but in some high-load situations, this could make the performance worse - because of cache miss in a single request. The real issue is that the master catchment in LAHI is not a real use case - towards which the configuration values are set. But since these are configurable values we can adjust them in the future.

@himeshr @vinayvenu
