### ISSUE TITLE
Make approval sync by entity

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#824]
### Workflow
Each non-voided form mapping has a parameter that says if approvals are enabled for an entity type. This will be used to request for both  ```GET /syncDetails``` and ```GET /entityApprovalStatus```
- ```GET /syncDetails``` will mark the entity to require sync if the user has permissions for the subject, and if there have been changes in the subject
- A new version of ```GET /entityApprovalStatus``` is added to avni-server that has two extra parameters - ```entityType``` and ```entityTypeUuid```. entityType can be of any one of ```EntityApprovalStatus.EntityType```. entityTypeUuid can be the subjectTypeUuid, programUuid, encounterTypeUuid or checklistDetailUuid
- This new version is used in the new avni-client for syncing data based on catchment, syncParameters or direct assignment
- The older version of approvals will still remain for backwards compatibility reasons

### Acceptance criteria
- Approval status is only fetched for the selected user's catchment, syncParameters or assigned entities
- Approval status is fetched only for entities that have view access for the user
- Approval status call is made only when there are changes in the approval status for entities

### Tech tasks
- Refactor server APIs /syncDetails and /entitySyncStatus
- Change client sync service to start using the new entity types

### Testing notes
- Ensure sync works fine.
- Ensure approval screen works fine
- Look up the database to ensure that only the right kind of approvals get into the system
- Use an older apk to ensure backward compatibility. Also should work as expected when the user upgrades with unsynced entity approval status in EntityQueue.  
- Export and import of subjects, encounters, etc - The newly added entityTypeUuid columns should be reflected in entity approval status tables
- Also check fast sync, reset sync etc.,
- Test approval status with multiple sync strategies - location, individual, sync parameters
- The calls for getting approval status of entity types should be made only when atleast for one corresponding form, approval status is enabled.
- ApprovalStatus workflow for Checklist Item is broken. Hence during development, testing was not done for this workflow. Ensure it is broken.
- When privileges removed, entity approval related entries for the privilege need to be removed from EntitySyncStatus and EntityApprovalStatus table.

**Comment by himeshr** [comment]
Investigation details on work to be done as part of this task from Himesh / Maha:

1. Create separate services which extend ScopeAwareService interface: 
SubjectApprovalStatusService
EncounterApprovalStatusService
ProgramEnrolmentApprovalStatusService
ProgramEncounterApprovalStatusService

2. Modify the EntityApprovalStatus table to include new column, EntityTypeId. Include migration logic for it.

3. Have a single EntityApprovalStatusRepository with methods, syncTypeIdSpec() which makes use of filter on:
a. entityTypeId == typeId
b. entityType == typeName (subType, encType, progEncType, prog, progOfChecklist)

**Comment by himeshr** [comment]
Client and Models side code changes:
 - Update the EntitySyncStatus save/update flow to
    1. also include entityTypeUUID.
    2. use entityType suffixed EntityApprovalStatus as the entityName
- Update the EntityApprovalStatus save/update flow to save entityTypeUUID

**Comment by mahalakshme** [comment]
During internal testing make sure the client migration works fine for the below case:
 when user upgrades the app with unsynced Entity Approval Status.

**Comment by petmongrels** [comment]
- Do not understand the change EntitySyncStatusService.setup method where the passed argument is always overwritten. Better to remove the argument if it is not required.
- We have to remove latestEntityApprovalStatus from Encounter etc, as this is a derived state and a source of defect by causing discrepancy between server and client state. This can be converted into a property.
- If entityTypeUuid is mandatory then why if condition in EntityApprovalStatusService.save?
-

**Comment by mahalakshme** [comment]
@petmongrels 
1. Fixed it-removed the unused parameter
2. For the server, latestEntityApprovalStatus is not relevant since we dont have approval workflow in webapp. So there is no chance of discrepancy so far. Do you have in mind any particular case where discrepancy can occur?
3. Say 2 users, A and B belong to the same catchment. A has updated the app, but not B. So B will not have entityTypeUuid. So when B syncs the approval status entry say entry1, entityTypeUuid will be null. If it is overwritten, then when A fetches with entityTypeUuid, entry1 will not be fetched. So the check is needed.

**Comment by petmongrels** [comment]
3. Can you put a comment, so that after few months we remove this condition
2. On client there are two pieces of information that determines which one is latestEntityApprovalStatus. a) latestEntityApprovalStatus b) the history of entity approval status for that entity. latestEntityApprovalStatus is derived and hence duplicate data. It is acting as a cache. But I don't know whether this cache required or not. We have had one case where these were out of sync. Since there is no inherent check it can happen again. Maybe we should handle this as a separate story. But this seems premature optimisation. @vinayvenu

**Comment by vinayvenu** [comment]
@petmongrels There is a separate card in analysis to fix this. There are some complications in removing the field that we can discuss there.

**Comment by mahalakshme** [comment]
@petmongrels @vinayvenu  I have created a card for point 3, https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/514 since there is one more deprecated code that can be removed. Have added it to 3.39 release so that we dont lose track of it. Need to add it to a relevant release or need to add a card for codepush and can add this within codepush epic card.

**Comment by vinayvenu** [comment]
Try syncing from staging with user approver@approval-test. 

Error - 'GroupPrivileges' has no property: 'entityTypeUuid'

Scenario - First time sync for a user that has privileges (not All Privileges).

**Comment by mahalakshme** [comment]
This is moved to code review ready for the above bug fix. Hence review the commit in client and model dated on 8th March alone.
