### ISSUE TITLE
[APF Odisha Uat]Auto-scroll is not working for village Profile form

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#832]
Village registration form is very large size .For that we developed  concept auto-scroll 
Organisation : APF Odisha Uat

**Comment by himeshr** [comment]
On investigation, i found 2 issues with respect to auto-scroll:

- Auto-scroll works when there is an error by scrolling to y offset relative to the parent (enclosing) view element. This results in in-accurate positioning when there are multiple parents and children in 1 page

- Auto-scroll is only triggered when there is a layout change (onLayout event for a view), which happens onPress of "Next" the first time, as it computes ValidationErrors. From the second onPress of "Next", no auto-scroll, as there is no change in layout(since all errors are already shown on screen and there is no layout change)

Based on above finding and keeping in mind the performance implication of recomputing validation-errors onPress of "Next", the current behaviour is optimal.

Since we use ScrollView and we do not have accurate position of errored element, caching the position also doesnot make much sense, as we might just scroll to some arbitrary location in the page and not to the actual errored element.

@vinayvenu  and @AchalaBelokar please let me know your thoughts on this.

**Comment by vinayvenu** [comment]
Closing based on this...
