### ISSUE TITLE
Immutable encounter error in the Claims Documentation

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#903]
As per the criteria if the encounter type Immutable is enabled the user fills the form only once  and for next process the form get filled automatically.If we want to edit the form we will use the previous button which will Navigate us to the form in the editable mode.
Excepted result : User should Navigate to claim documentation in the editable mode.
Actual result : User Navigated to the dashboard
Test data :
User: AchalaB@poweruat
Step 1: 
opening one user 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/fa52a403-a330-44ad-8ec9-e6e4f7506287)

step 2:
Clicking on the claim documentation
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d4fa2d24-6407-4223-99ea-3f404b846f80)

Step 3: 
Click on the previous excepted result :User should Navigate to claim documentation in the editable mode.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/71040c00-4b9f-422d-9d63-559a4941af9e)

**Comment by sachsk** [comment]
@Dinesh2019 this is an implementation-specific issue.
This form is mapped for ``Old Age Pension Benefit``  but now it's mapped to ``Marriage Assistance`` . and this individual is in the ``Old Age Pension Benefit`` program so the form is not available for this individual and because of that user cant able to edit the form.
