### ISSUE TITLE
Voided program assignment causes association error

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#914]
In LAHI production organisation ("Lend a hand India") for any user, there is voided program **Karigar (voided~564)** and individuals with this program enrolment were assigned to users. These users were not able to sync the app, PFA for more details.

Ideally the program enrolment should have synced.

![Screenshot from 2023-03-27 12-44-13.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/f5b4ffec-7c24-405d-96c5-1ae589dbd9b9)

**Comment by vinayvenu** [comment]
- We need to ensure voided programs do not cause association error
- In this case, the program was created by mistake, so all related entries (program enrolment, program encounter etc) should be "deleted" (not voided)

**Comment by petmongrels** [comment]
@nupoorkhandelwal can you please put env, user details

**Comment by nupoorkhandelwal** [comment]
LAHI org on production.

**Comment by himeshr** [comment]
I am unable to re-produce with "mel@lahi" user on prod avni-client. Based on below commands, that is the only user with a user_subject_assignment for the voided program..

**Commands:**

set role lahi;

select * from organisation;
select * from organisation_config where organisation_id = 186;

select * from program where id = 482;

select * from program_enrolment where program_id = 482;

select * from user_subject_assignment usa join users u on usa.user_id = u.id
                        and usa.subject_id in (1207151, 1207684);

select * from users where id = 5912;

select * from individual where id = 1207684;

**Comment by himeshr** [comment]
### Analysis Notes:



#### The encounter for which sync fails, which is already voided, its related to program_enrolment_id = 255647 and encounter_type = 1810
select * from program_encounter where uuid = '988cc628-44fe-4ea2-b485-d2624cdcf5de';

#### Its mapped to encounter_type which is not voided
select * from encounter_type where id = 1810;

#### Its mapped to program_enrolment which is also voided, its related to program_id = 564
select * from program_enrolment where id = 255647;

#### This is mapped to a voided program "Karigar" which is also voided
select * from program where id = 564;

#### This Program has only voided form_mappings
select * from form_mapping join form f on form_mapping.form_id = f.id where entity_id = 564 and f.form_type = 'ProgramEnrolment' and form_mapping.is_voided = true;

#### Based on above data, the encounter should not have been attempted to sync as its related program's form_mapping is voided. But, the issue is caused due to re-use of the same encounter_type for 2 different programs (564, 613), Program with id 613 has 2 non-voided entries that map to forms with id in (5289, 5290)
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;

#### The program "Karigar" which is not voided
select * from program where id = 613;

#### There are forms corresponding to the
select * from form where id in (5289, 5290);

#### Because of the below 2 non-voided form-mappings with observations_type_entity_id = 1810,
 during sync we attempt to sync encounters that belong to encounter_type_id = 1810, uuid = 3acfc167-0124-4292-8c66-8fdb3e34ef95
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;
select * from encounter_type where id = 1810;

####  DEBUG  [2:32:31:250] [Requests][Debug] GET: https://server.avniproject.org/programEncounter?programEncounterTypeUuid=3acfc167-0124-4292-8c66-8fdb3e34ef95&lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-04-11T09:05:40.087Z&size=100&page=0
  INFO  [2:32:31:251] [AuthService][Info] Found token
Analysis Notes:



#### The encounter for which sync fails, which is already voided, its related to program_enrolment_id = 255647 and encounter_type = 1810
select * from program_encounter where uuid = '988cc628-44fe-4ea2-b485-d2624cdcf5de';

#### Its mapped to encounter_type which is not voided
select * from encounter_type where id = 1810;

#### Its mapped to program_enrolment which is also voided, its related to program_id = 564
select * from program_enrolment where id = 255647;

#### This is mapped to a voided program "Karigar" which is also voided
select * from program where id = 564;

#### This Program has only voided form_mappings
select * from form_mapping join form f on form_mapping.form_id = f.id where entity_id = 564 and f.form_type = 'ProgramEnrolment' and form_mapping.is_voided = true;

#### Based on above data, the encounter should not have been attempted to sync as its related program's form_mapping is voided. But, the issue is caused due to re-use of the same encounter_type for 2 different programs (564, 613), Program with id 613 has 2 non-voided entries that map to forms with id in (5289, 5290)
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;

#### The program "Karigar" which is not voided
select * from program where id = 613;

#### There are forms corresponding to the
select * from form where id in (5289, 5290);

#### Because of the below 2 non-voided form-mappings with observations_type_entity_id = 1810, during sync we attempt to sync encounters that belong to encounter_type_id = 1810, uuid = 3acfc167-0124-4292-8c66-8fdb3e34ef95
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;
select * from encounter_type where id = 1810;

####  DEBUG  [2:32:31:250] [Requests][Debug] GET: https://server.avniproject.org/programEncounter?programEncounterTypeUuid=3acfc167-0124-4292-8c66-8fdb3e34ef95&lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-04-11T09:05:40.087Z&size=100&page=0
####  INFO  [2:32:31:251] [AuthService][Info] Found token
####  ERROR  SyncComponent-Sync ProgramEncounter{uuid='988cc628-44fe-4ea2-b485-d2624cdcf5de'} is unable to find
####  ProgramEnrolment{uuid='23f4b86b-514b-48d8-98cb-554450ca930b'}, {"errorCode":"Association error 10","errorText":"ProgramEncounter{uuid='988cc628-44fe-4ea2-b485-d2624cdcf5de'}
####  is unable to find ProgramEnrolment{uuid='23f4b86b-514b-48d8-98cb-554450ca930b'}","line":118433,"column":29,
####  "sourceURL":"http://localhost:8081/index.android.bundle?platform=android&dev=true&minify=false&app=com.openchsclient&modulesOnly=false&runModule=true"}

#### At this point we return to the encounter for which sync fails, which is already voided, its related to encounter_type = 1810 and program = 564 and not program = 613. While our intention is to get encounters of type encounter_type = 1810 and program = 613, which is not factored in, due to missing program filter program_id = 613 and not program_id = 564.
select * from program_encounter where uuid = '988cc628-44fe-4ea2-b485-d2624cdcf5de';


### Analysis Conclusion:
 #### As, we do not have capability to include relatedEntityType and relatedEntityTypeUUID information while creating SyncableItem, we'll not be able to provide additional information to client, to make it request for ProgramEncounters of specific Program for given encounterTypeUUID.
public class SyncableItem {
    private String name;
    private String entityTypeUuid;
}
 #### Therefore, the only recourse to correct this issue, is to delete the transactional data related to the voided ProgramEncounters and ProgramEnrolments and then attempt fresh sync.

**Comment by himeshr** [comment]
Analysis Notes:



-- The encounter for which sync fails, which is already voided, its related to program_enrolment_id = 255647 and encounter_type = 1810
select * from program_encounter where uuid = '988cc628-44fe-4ea2-b485-d2624cdcf5de';

-- Its mapped to encounter_type which is not voided
select * from encounter_type where id = 1810;

-- Its mapped to program_enrolment which is also voided, its related to program_id = 564
select * from program_enrolment where id = 255647;

-- This is mapped to a voided program "Karigar" which is also voided
select * from program where id = 564;

-- This Program has only voided form_mappings
select * from form_mapping join form f on form_mapping.form_id = f.id where entity_id = 564 and f.form_type = 'ProgramEnrolment' and form_mapping.is_voided = true;

-- Based on above data, the encounter should not have been attempted to sync as its related program's form_mapping is voided.
-- But, the issue is caused due to re-use of the same encounter_type for 2 different programs (564, 613),
-- Program with id 613 has 2 non-voided entries that map to forms with id in (5289, 5290)
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;

-- The program "Karigar" which is not voided
select * from program where id = 613;

-- There are forms corresponding to the
select * from form where id in (5289, 5290);

-- Because of the below 2 non-voided form-mappings with observations_type_entity_id = 1810,
-- during sync we attempt to sync encounters that belong to encounter_type_id = 1810, uuid = 3acfc167-0124-4292-8c66-8fdb3e34ef95
select * from form_mapping where entity_id in (564, 613) and observations_type_entity_id = 1810;
select * from encounter_type where id = 1810;

--  DEBUG  [2:32:31:250] [Requests][Debug] GET: https://server.avniproject.org/programEncounter?programEncounterTypeUuid=3acfc167-0124-4292-8c66-8fdb3e34ef95&lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-04-11T09:05:40.087Z&size=100&page=0
--  INFO  [2:32:31:251] [AuthService][Info] Found token
--  ERROR  SyncComponent-Sync ProgramEncounter{uuid='988cc628-44fe-4ea2-b485-d2624cdcf5de'} is unable to find
--  ProgramEnrolment{uuid='23f4b86b-514b-48d8-98cb-554450ca930b'}, {"errorCode":"Association error 10","errorText":"ProgramEncounter{uuid='988cc628-44fe-4ea2-b485-d2624cdcf5de'}
--  is unable to find ProgramEnrolment{uuid='23f4b86b-514b-48d8-98cb-554450ca930b'}","line":118433,"column":29,
--  "sourceURL":"http://localhost:8081/index.android.bundle?platform=android&dev=true&minify=false&app=com.openchsclient&modulesOnly=false&runModule=true"}

-- At this point we return to the encounter for which sync fails, which is already voided,
-- its related to encounter_type = 1810 and program = 564 and not program = 613.
-- While our intention is to get encounters of type encounter_type = 1810 and program = 613,
-- which is not factored in, due to missing program filter program_id = 613 and not program_id = 564.
select * from program_encounter where uuid = '988cc628-44fe-4ea2-b485-d2624cdcf5de';


## Analysis Conclusion:
 - As, we do not have capability to include relatedEntityType and relatedEntityTypeUUID information while creating SyncableItem, we'll not be able to provide additional information to client, to make it request for ProgramEncounters of specific Program for given encounterTypeUUID.
public class SyncableItem {
    private String name;
    private String entityTypeUuid;
}
 - Therefore, the only recourse to correct this issue, is to delete the transactional data related to the voided ProgramEncounters and ProgramEnrolments and then attempt fresh sync.

**Comment by himeshr** [comment]
Deleted the transactional data related to the voided ProgramEncounters and ProgramEnrolments and then attempted fresh sync. Issue was resolved. After that un-voided the UserSubjectAssignments.

Above specified changes done as part of 
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lahi/50
