### ISSUE TITLE
Display of Question Group Concepts in Filters List can be removed.

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#992]
Question group concepts are being displayed in the filters list, even though they do not have any values to filter by
Steps to reproduce
1. login to avin app
2. click on the app designer
3. go to offline dasboard
4. click on edit
5. below we have the add filter option
6. it will popup the window named as create filter
7. Enter the filter name ,Select type as concept
8. select question group concept
9.add the filter

### Solution - Question groups should not be available to be added in filters. 

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/b385031a-b950-444e-bfde-7c9895a92fcd)

to do:
- Export
- validations

**Comment by vinayvenu** [comment]
@Dinesh2019 we need to figure out specific concept data types.

**Comment by mahalakshme** [comment]
@vinayvenu these are the concept types that we are supporting now in dashboard filters: Numeric, Text, Notes, Coded, Date, DateTime, Time, Id, Encounter, Location, GroupAffiliation, Subject, Duration - Is that fine?

found that in search filters we are supporting some irrelevant concept types like NA. Once the relevant concepts is finalised for this, if it makes sense, we can update the same there as well

**Comment by vinayvenu** [comment]
@mahalakshme - Datatypes to be supported - Numeric, Text, Notes, Coded, Date, DateTime, Id, PhoneNumber

**Comment by vinayvenu** [comment]
@mahalakshme - Datatypes to be supported - Numeric, Text, Notes, Coded, Date, DateTime, Id, PhoneNumber

I am not sure how we can support Encounter, Location, GroupAffiliation, Subject and Duration. 

Even in search, these do not make sense.

**Comment by mahalakshme** [comment]
@vinayvenu Vinay have added the types Numeric, Text, Notes, Coded, Date, DateTime, Time, Id. Found that Location filter didnt work. Also GroupAffiliation, Subject, Duration and PhoneNumber were not allowed in search filters(for concept) in code. So felt it might not work here. Didnt test everything since didnt want to spend much time unless needed.

but need to make sure we support relevant concepts for the APF usecase(seems like subject and location support is needed) shared by Arjun: The main type of user who needs filters currently is called "Supervisor"
Supervisors are responsible for providing supportive supervision to "Poshan Sathi".  One supervisor can supervise 1-5 Poshan Sathis. 
Poshan Sathis are responsible for registering beneficiaries and completing visits on time.
Supervisors need to check regularly whether visits are being completed on time. If they are in a particular area, they need to filter the dashboard cards for a particular Poshan Sathi. We do not have filter for user right now. So they will filter by location (mapped to user usually one is to one). They may also want to see just a particular type of visit or just a particular type of beneficiary. 

Example If Poshan Sathi is Arjun and supervisor is Dinesh, Dinesh may want to see all the ANC visits that are overdue to be performed by Arjun. 

Looks like some analysis is needed to decide on what concepts to support. should I move this to In Analysis.

**Comment by mahalakshme** [comment]
@vinayvenu have updated to "In Analysis"

**Comment by vinayvenu** [comment]
Support for subject and location can be tackled as a separate piece. We can
move this card forward.

**Comment by mahalakshme** [comment]
@vinayvenu okay currently then I am not adding any code in server as well as client for Subject and Location concept data types to prevent broken pieces.

**Comment by Dinesh2019** [comment]
- [x] For this card as per the analysis we are not displaying the concepts of other types excpet these type concept Numeric, Text, Notes, Coded, Date, DateTime, Time, Id filters --- this is done

- [ ] we have to test the behavior of those concept type(Numeric, Text, Notes, Coded, Date, DateTime, Time, Id filters)
